# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ThesisARTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ARCL','1.0.2'
  # Pods for ThesisARTest

end
